# SPDX-FileCopyrightText: 2009 Fermi Research Alliance, LLC
# SPDX-License-Identifier: Apache-2.0

# This workflow can be triggered w/ a dispatch event, e.g.
# curl -X POST -H "Accept: application/vnd.github.v3+json" \
#  https://api.github.com/repos/glideinwms/glideinwms/dispatches \
#  -d '{"event_type":"docker-build"}'

name: Build and Push Docker image (CI)

on:
  push:
    branches: [ master, master_ci ]
    path:
      - build/packaging/containers/gwms-ci-sl7/Dockerfile
      - build/packaging/containers/gwms-ci-sl7/Dockerfile
  repository_dispatch:
    types:
      - docker-build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: make date tag
      id: mkdatetag
      run: echo "::set-output name=dtag::$(date +%Y%m%d-%H%M)"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        context: build/packaging/containers
        file: build/packaging/containers/gwms-ci-sl7/Dockerfile
        tags: glideinwms/gwms-ci-sl7:latest
