# SPDX-FileCopyrightText: 2009 Fermi Research Alliance, LLC
# SPDX-License-Identifier: Apache-2.0

name: Build and Push Docker image (CI)

on:
  push:
    branches: [ master, master_ci ]
    path:
      - 'build/packaging/containers/*'
      - '.github/workflows/docker_build.yml'
  repository_dispatch:
    types:
      - dispatch-build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: make date tag
      id: mkdatetag
      run: echo "::set-output name=dtag::$(date +%Y%m%d-%H%M)"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        context: build/packaging/containers
        file: build/packaging/containers/gwms-ci-sl7/Dockerfile
        tags: glideinwms/gwms-ci-sl7:latest
